module.exports.descriptors = [
    'Forest',
    'Acient',
    'Petrified',
    'Roaring',
    'Casecade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Ground Camp',
    'Horse Camp',
    'Ghost Camp',
    'River',
    'Creek',
    'Bay',
    'Sands',
    'Cliffs',
    'Hollow',
    'Hunting',
    'Mule Camp',
    'Backcountry',
]